/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rumahsakit.form;

/**
 *
 * @author ADHE
 */
public class FormUtama extends javax.swing.JFrame {

    /**
     * Creates new form FormUtama
     */
    public FormUtama() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tabelDokter = new javax.swing.JButton();
        tabelPenyakit = new javax.swing.JButton();
        tabelPasien = new javax.swing.JButton();
        tabelObat = new javax.swing.JButton();
        tabelTransaksi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Disco Diva", 0, 48)); // NOI18N
        jLabel1.setText("Rumah Sakit");

        tabelDokter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tabelDokter.setText("Manage DOKTER");
        tabelDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabelDokterActionPerformed(evt);
            }
        });

        tabelPenyakit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tabelPenyakit.setText("Manage PENYAKIT");
        tabelPenyakit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabelPenyakitActionPerformed(evt);
            }
        });

        tabelPasien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tabelPasien.setText("Manage PASIEN");
        tabelPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabelPasienActionPerformed(evt);
            }
        });

        tabelObat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tabelObat.setText("Manage OBAT");
        tabelObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabelObatActionPerformed(evt);
            }
        });

        tabelTransaksi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tabelTransaksi.setText("Manage TRANSAKSI");
        tabelTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabelTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                        .addComponent(tabelTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                        .addComponent(tabelDokter))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                        .addComponent(tabelPenyakit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tabelPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addGap(224, 224, 224))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tabelObat)
                        .addGap(263, 263, 263))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(128, 128, 128))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tabelDokter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabelPenyakit)
                .addGap(10, 10, 10)
                .addComponent(tabelPasien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelObat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelTransaksi)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabelDokterActionPerformed
        this.setVisible(false);
        FormDokter fDokter = new FormDokter();
        fDokter.setVisible(true);
    }//GEN-LAST:event_tabelDokterActionPerformed

    private void tabelPenyakitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabelPenyakitActionPerformed
        this.setVisible(false);
        FormPenyakit fPenyakit = new FormPenyakit();
        fPenyakit.setVisible(true);
    }//GEN-LAST:event_tabelPenyakitActionPerformed

    private void tabelPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabelPasienActionPerformed
        this.setVisible(false);
        FormPasien fPasien = new FormPasien();
        fPasien.setVisible(true);
    }//GEN-LAST:event_tabelPasienActionPerformed

    private void tabelObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabelObatActionPerformed
        this.setVisible(false);
        FormObat fObat = new FormObat();
        fObat.setVisible(true);
    }//GEN-LAST:event_tabelObatActionPerformed

    private void tabelTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabelTransaksiActionPerformed
        this.setVisible(false);
        FormTransaksi fTransaksi = new FormTransaksi();
        fTransaksi.setVisible(true);
    }//GEN-LAST:event_tabelTransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton tabelDokter;
    private javax.swing.JButton tabelObat;
    private javax.swing.JButton tabelPasien;
    private javax.swing.JButton tabelPenyakit;
    private javax.swing.JButton tabelTransaksi;
    // End of variables declaration//GEN-END:variables
}
